export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
// APOD
export const APOD_SAVE = "APOD_SAVE";
export const APOD_DATE_UPDATE = "APOD_DATE_UPDATE";
export const APOD_HOME_SAVE = "APOD_HOME_SAVE";
// EPIC
export const SAVE_EPIC_DATES = 'SAVE_EPIC_DATES';
export const EPIC_FILTER_UPDATE = 'EPIC_FILTER_UPDATE';
export const EPIC_LIST_UPDATE = 'EPIC_LIST_UPDATE';
export const EPIC_LIST_CLEAR = 'EPIC_LIST_CLEAR';
// EARTH
export const UPDATE_EARTH_FILTERS = 'UPDATE_EARTH_FILTERS';
export const STORE_EARTH_DATA = 'STORE_EARTH_DATA';
export const CLEAR_EARTH_DATA = 'CLEAR_EARTH_DATA';
