export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';

//APOD
export const LOAD_APOD_START = "LOAD_APOD_START";
export const LOAD_APOD_SUCCESS = "LOAD_APOD_SUCCESS";
export const LOAD_APOD_ERROR = "LOAD_APOD_ERROR";

//EPIC
export const SAVE_EPIC_DATES = 'SAVE_EPIC_DATES';
export const EPIC_FILTER_UPDATE = 'EPIC_FILTER_UPDATE';
export const EPIC_LIST_UPDATE = 'EPIC_LIST_UPDATE';
